apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-logging
  labels:
    component: kibana
    role: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 5601
  selector:
    component: kibana
    role: frontend
