---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: kube-logging
  name: elasticsearch
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: master
  replicas: 3
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: rolindroy/elasticsearch:6.6.0
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
        command: [ "bin/elasticsearch" ]
        env:
        - name: CLUSTER_NAME
          value: "Production Cluster"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: NUMBER_OF_MASTERS
          value: "2"
        - name: NETWORK_HOST
          value: "_eth0_, _local_"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: DISCOVERY_SERVICE
          value: elasticsearch-discovery
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - mountPath: /data
          name: data
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: gp2
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 2Gi
