---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-logging
  labels:
    component: kibana
    role: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      component: kibana
      role: frontend
  template:
    metadata:
      labels:
        component: kibana
        role: frontend
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.6.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
